### ISSUE TITLE
Buffs not working

### ISSUE THREAD

**Issue by Rockouthard** [DestinyNetwork/DRIssues#1]
the invocation buffs with the end crystals dont work right i got a 5-11 axe and i got strength 50% and i was doing 5 damage at points still also unlimited sprint is still a thing that probably needs to be fixed but not gae breaking

**Comment by Rockouthard** [comment]
game breaking lol
 srry for spelling

**Comment by Rockouthard** [comment]
also when u die u lose all of ur armor and weapons

**Comment by Kryns** [comment]
Lvl wipe when u log out and log again on the server.

**Comment by Kryns** [comment]
Untradeable potions (idk if normal) dont regen the hp

**Comment by Kryns** [comment]
I died and dont lost durability/dont lost my inv

**Comment by UnoWild** [comment]
As per request please keep all submissions separate. 
ONE ISSUE PER REPORT.

**Comment by UnoWild** [comment]
Multiple issues, commented on. Closing
