### ISSUE TITLE
Guild armor dye

### ISSUE THREAD

**Issue by xPoolio92** [DestinyNetwork/DRIssues#15]
Pricing needs work

**Comment by UnoWild** [comment]
This is about the Bottle to dye the armor.

**Comment by MrUNSC** [comment]
The item vendor GUI says that guild dye costs 1,000g, while if you try to purchase it it says that it is 200g

**Comment by UnoWild** [comment]
Orbs of Piece are lisyted as 1,000 and also try to charge you 1,000 BUT,
should be sold for 400
