### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by xPoolio92** [DestinyNetwork/DRIssues#36]
When logging into the server, It says you can choose the server you want to be on with /shard
/shard is not available to use as a default player

It also says Hey <Name> "Click this to join our teampseak" 
When you click it nothing happens.

The website it advertises is www.dungeonrealms.com
The real website is www.dungeonrealms.net

**Comment by TheKayaba** [comment]
As submission guidelines provide on the main page.. One bug PER submission. This submission will be ignored and deleted. Repeat abuse of this system will result in banning of usage of the issue tracking system and removal of closed beta access.

**Comment by TheKayaba** [comment]
Issue was mistakenly marked as invalid... Fixing
