### ISSUE TITLE
Potion Bugs

### ISSUE THREAD

**Issue by Adamchow1** [DestinyNetwork/DRIssues#40]
the post you get when you start after starter island and the pots you get after you die don't work

**Comment by Adamchow1** [comment]
sometimes the pots work but not all the time

**Comment by Adamchow1** [comment]
ok found the pot bug .  if you log out with pots in your hand hand log back in later your pots wont be able to be used

**Comment by UnoWild** [comment]
Please only post ONE issue per Report

**Comment by TheKayaba** [comment]
DO NOT POST DUPLICATES. Simply add evidence to existing bugs!
