### ISSUE TITLE
Fishing bug

### ISSUE THREAD

**Issue by Pelemesh** [DestinyNetwork/DRIssues#44]
BAsicly old fishing bug when you can spam RClick and catch multible fish in a row.
Reproduce: Get fishing rod, go to fishing pond, wait till fish baits, then instead of clicking once use macro(LOL) or just click fast.

**Comment by UnoWild** [comment]
I did this myself and I could not spam level up the Rod, the rod does give a lot of xp at first so is easy to level it up.

**Comment by SyntheticSponge** [comment]
I have tested this myself as well, and can spam level my rod.
