### ISSUE TITLE
Double Click causing no mob KB

### ISSUE THREAD

**Issue by egimfun** [DestinyNetwork/DRIssues#47]
https://gyazo.com/ac8c90173ae92b5b595762396fc4c228
first mob is single click , second is double click.  its a type of macro, im sure you know

**Comment by UnoWild** [comment]
Are you macroing ?

**Comment by egimfun** [comment]
double click, obviously for the purpose of testing....

**Comment by monetizeme** [comment]
Please do not break the rules while testing, unless a DEV or GM asks you to.
