### ISSUE TITLE
no bow knockback

### ISSUE THREAD

**Issue by egimfun** [DestinyNetwork/DRIssues#48]
when you left click with a bow its meant to do a bunch of knockback and use up a ton of energy... it takes the energy but doesn't give and knockback

**Comment by UnoWild** [comment]
Bows are for shooting arrows, they are not a mele weapon.

**Comment by egimfun** [comment]
if you actually played open beta you would know that bows have the ability to knock back mobs and players upon left click.  this isn't "restore dr to what uno thinks it should be", its restore it to open beta

**Comment by UnoWild** [comment]
2nd comment is invalid, obviously we all played.
These comments are not needed in this application, please refrain from using them as your personal sounding board
