### ISSUE TITLE
teleport book stack bug

### ISSUE THREAD

**Issue by Adamchow1** [DestinyNetwork/DRIssues#54]
if you shift click tp books into the merchant. if they have the same name they will stack and stay stacked. if you use the book it will unstack them all and put them in your bag if you have open slots if you don't have enough slots open the items will just drop to the ground and you will lose them when you tp away

**Comment by MrUNSC** [comment]
This is intended (I think). I was talking to Kayaba in TS earlier, where he said that he made it so TP books no longer stack.

**Comment by UnoWild** [comment]
Stacking them that was allowed in old DR and was the only way to stack the Books at the time. Stacked books would often trigger more than one if they are in your hotbar when you attempt to use one though.
