### ISSUE TITLE
Armor Breaking on Death

### ISSUE THREAD

**Issue by DefNotScreaming** [DestinyNetwork/DRIssues#61]
After dying the durability that you lose is sometimes random and incorrect. Multiple times I have lost complete sets due to this bug.
My armor before death: https://gyazo.com/74b8258cd80140a4bff950ae5dc3831a
My armor one minute later after dying: https://gyazo.com/7ac121a0bb32f55e0c43fd7e89f50be2

**Comment by UnoWild** [comment]
Thats part of the game. Your armor takes an additional duro.
Unless there is additional info

**Comment by DefNotScreaming** [comment]
Updated
