### ISSUE TITLE
if you hit a mob in a safe zone

### ISSUE THREAD

**Issue by Whyismy** [DestinyNetwork/DRIssues#64]
Your weapon dissapears the second they return to their spawn point, i dont know if this is a punishment to people who try to safe farm, but this is a little harsh :P

**Comment by MrUNSC** [comment]
It doesn't disappear, but it acts as if your using vanilla durability and doesn't reset (quite devastating on T1/2/5 weapons). This is pretty harsh as some areas such as Tripoli you can't easily tell if its a safezone or not.

**Comment by TheKayaba** [comment]
MrUNSC is correct.. Therefore I'm closing this.
