### ISSUE TITLE
Realm Deaths

### ISSUE THREAD

**Issue by DefNotScreaming** [DestinyNetwork/DRIssues#71]
If you get killed by a player or /suicide inside of a realm, you lose ALL of your items including your first slot and equipped armor. Oh, also all permanent or untradeable items disappear, including e-cash items and horses/mules.

**Comment by Whyismy** [comment]
Thats not only in realms, when you die you lose everything no matter what. Probably because alignments arent in the game atm

**Comment by DefNotScreaming** [comment]
This is not correct, keepinventory is on.
