### ISSUE TITLE
Realm portals

### ISSUE THREAD

**Issue by Whyismy** [DestinyNetwork/DRIssues#90]
Realm portals get stuck sometimes??

![Broken portal](https://i.gyazo.com/09731f43a616e404e2cf55a916471732.png)

When you use the portal, it says that it isnt linked to a realm.

**Comment by UnoWild** [comment]
Please title your reports based on what the issue is, then in the comments wrote all you want. :-)

**Comment by Whyismy** [comment]
ok daddy
